## Model
model: 'cond_siren'
w0: 1.0
w0_initial: 8.0
layers: [4, 256, 256, 256, 1]  # 5x256 as in the SIREN paper: https://arxiv.org/pdf/2006.09661.pdf (pdf page 21)
seed: 17
level_set: 0
nx: 3 # input is 3D
ny: 1 # output is a scalar
nz: 1
batch_size: 1 # usually denoted as bz in the code
plot_n_shapes: 1 # must not be bigger than batch_size
use_x_and_z_arg: True  # used when creating the stateless model\
# reset_zlatents_every_n_epochs: 1  # uncomment to set; not set means the latents are kept fix
z_sample_interval: [-0.1, 0.1]
z_sample_method: 'uniform'  # any of ['uniform', 'normal', 'w0-informed', 'linspace']

## Constraints
problem: 'grid_world'
dataset_dir: '/scratch/rhm4nj/cral/cral-ginn/ginn/myvis/data_gen/grid_world1'
envelope_sample_from: 'exterior'
## Number of points to sample

n_points_domain: 16384 
n_points_interfaces: 8192
n_points_normals: 8192
n_points_envelope: 32768
n_points_descent: 16384
# n_points_obstacles: 128
n_points_outer: 4096
n_points_find_surface: 4096
n_points_find_cps: 4096

#### HYPERPARAMETERS ####

## Loss-balancing
lambda_bc: 1
lambda_dom: 1
lambda_outer_env: 1
lambda_outer_unif: 0
lambda_outer_var: 0.0
lambda_env: 0 # using outer losses instead
lambda_normal: 1.0e-6
# lambda_normal: 1.0e-6
lambda_obst: 0.0
lambda_descent: 0
lambda_small_control: 0
# global
lambda_vx: 1.0e-4
lambda_vxx: 1.0e-4
lambda_bound: 0
lambda_eikonal: 1.0e-9
lambda_scc: 1.0e-2
lambda_div: 0  # too low for resetting z every epoch; testing 1.0e-6 on 24.1.2024 
lambda_curv: 1.0e-7  # off by default; goood value is around 1.0e-7-1.0e-9

cbf_lambda: -1.0e-2
cbf_relaxation_penalty: 5
controller_step_range: [0.5, 2]
n_controller_steps: 10
outer_target: 0
interface_delta: 0
min_control_norm: 0.5
loss_optim: 'fixed' #fixed, loss_balancer, gradnorm
# min_outer_val: 0.5
min_env_val_inner: 1.0e-2
min_env_val_outer: 0.1
max_domain_val: -0.1
env_val_tol: 0.1

# related
diversity_loss_eps: 1.0e-4

## Outer optimization loop
max_epochs: 250
loss_thresh: 1.0e-3 # percentage
min_loss_thresh: 1.0e-6

lr: 0.001  # IMPORTANT: is usually 0.001; it was only decreased for the demo
## scheduler
use_scheduler: True
scheduler_gamma: 0.5
decay_steps: 1000
# gradient clipping
grad_clipping_on: True
grad_clip: 0.5
# autoclip: https://arxiv.org/abs/2007.14469
auto_clip_on: False
auto_clip_percentile: 0.8
auto_clip_hist_len: 50
auto_clip_min_len: 50

#### CONNECTIVITY ####

## Critical points
lr_find_cps: 0.01
lr_adjust_cps: 0.001 # should be much smaller than lr_find_cps
max_iter_find_cps: 1000
remove_penalty_points_outside_envelope: True
# check_times_proximity_mask: [20, 50, 200, 500]
# check_times_proximity_mask: []

## Saddle point descent
n_iter_saddle_descent: 1000
lr_saddle_descent: 0.03
perturbation_saddle_descent: 0.01
stop_grad_mag_saddle_descent: 1.0e-5
check_interval_grad_mag_saddle_descent: 5

# recalc_cps_every_n_epochs: 20
recalc_cps_every_n_epochs: 1  # For SimJEB, we almost never can reuse the graph and waste too much time on trying to do so
plot_every_n_epochs: 10
plot_secondary_plots_every_n_epochs: 500  # must be multiple of plot_every_n_epochs, otherwise the shape is not recomputed


## Clustering
dbscan.y_x_mag: 1.0e-5  # filter out points with high gradient magnitude (not converged)
dbscan.eps: 0.05 # spatial extent for clustering

## Graph algorithm
graph_algo_inv_dist_eps: 0.1

## SCC algorithm
scc_penalty_norm_eps: 1.0e-4

#### DIVERSITY ####

## Distance in function space
recompute_surface_pts_every_n_epochs: 10
find_surface_pts_n_iter: 200
lr_find_surface: 0.01
adam_betas_find_surface: [0.9, 0.999]
find_surface_pts_prec_eps: 1.0e-6  ## may stop if all the points are either outside of the boundary or epsilon-close to the surface
find_surface_pts_converged_interval: 10
reweigh_surface_pts_close_to_interface: True
reweigh_surface_pts_close_to_interface_cutoff: 0.2
reweigh_surface_pts_close_to_interface_power: 2.0

#### Curvature ####
strain_curvature_clip_max: 1.0e+3

#### LOGGING ####

## Wandb
wandb_experiment_name: 'grid_cond_siren'
wandb_save_dir: "all_runs/wandb"

## Weights
# model_save_path: '_saved_models'
model_save_path: 'all_runs/models/grid_world'
load_model: False
model_load_path: '/scratch/rhm4nj/cral/ginn/all_runs/models/cond_siren/2024_10_10-23_41_01/2024_10_10-23_41_01-9cu3lc4a_2300.pth'

save_every_n_epochs: 10

## Timer
timer_print: False
timer_accumulate: True ## record and print the accumulated timings at the end

## Multi-processing
num_workers: 0  # 0 means no multi-processing

## Plotting
fig_path: 'img/simjeb/cond_siren' ## must be set if fig_show True
fig_size: [12, 7]
fig_show: True
fig_save: False
fig_wandb: False
fig_pynb: True  # show figure inline in the notebook
force_saving_shape: False ## TODO
show_colorbar: True
mc_resolution: 128

## Specific plots

## primary plots
plot_shape: True
# plot_penalty_points_only_in_envelope: True
# plot_grad_mag_hist: False

## secondary plots
# plot_start_points_to_find_cps: True
# plot_cp_descent_refinement: True
# plot_cp_descent_recomputation: True
# plot_trajectories_every_n_iter: 100
# plot_cps: True
# plot_cp_candidates: True
# plot_perturbed_sps: False
# plot_characterized_cps: True
# plot_saddle_descent: True
# plot_edges: True
# plot_surfnet_graph: True
# plot_intermediate_wd_graph: True
# plot_sub_and_neighbor_wd_graph: True
# plot_penalty_points: True
# plot_surface_points: True
# plot_wd_graph: True
# plot_surface_descent: True