name: ginn_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - setuptools
  - wheel
  - libffi
  - libgcc-ng
  - libzlib
  - openssl
  - readline
  - tk
  - ncurses
  - ca-certificates
  - pip:
      - casadi==3.7.0
      - clarabel==0.10.0
      - click==8.1.8
      - colorlog==6.9.0
      - contourpy==1.3.2
      - cripser==0.0.15
      - cvxpy==1.6.5
      - cvxpylayers==0.1.5
      - diffcp==1.1.4
      - docker-pycreds==0.4.0
      - ecos==2.0.14
      - einops==0.8.1
      - embreex==2.17.7.post6
      - fast-simplification==0.1.10
      - fonttools==4.57.0
      - gitpython==3.1.44
      - imageio==2.37.0
      - joblib==1.4.2
      - jupyter
      - jupyter-console
      - k3d==2.16.1
      - kappaconfig==1.0.31
      - lightning-utilities==0.14.3
      - manifold3d==3.0.1
      - mapbox-earcut==1.0.3
      - matplotlib==3.10.1
      - networkx==3.3
      - numpy==2.1.2
      - osqp==1.0.3
      - pandas==2.2.3
      - pillow==11.0.0
      - plyfile==1.1
      - protobuf==6.30.2
      - psutil==7.0.0
      - pyarrow==19.0.1
      - pycollada==0.9
      - pytorch-lightning==2.5.1.post0
      - pyyaml==6.0.2
      - requests==2.32.3
      - rtree==1.4.0
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - scs==3.2.7.post2
      - seaborn==0.13.2
      - sentry-sdk==2.27.0
      - setproctitle==1.3.5
      - shapely==2.1.0
      - sympy==1.13.1
      - torch==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - torchaudio==2.6.0+cu124
      - torchmetrics==1.7.1
      - tqdm==4.67.1
      - trimesh==4.6.8
      - triton==3.2.0
      - typing-extensions==4.12.2
      - vhacdx==0.0.8.post2
      - wandb==0.19.10